# This file sets the basic flags for the RUC compiler
if(NOT CMAKE_RUC_COMPILE_OBJECT)
	set(CMAKE_RUC_COMPILE_OBJECT "cp <SOURCE> <OBJECT>")
endif()

if(NOT CMAKE_RUC_LINK_EXECUTABLE)
	set(CMAKE_RUC_LINK_EXECUTABLE "<CMAKE_RUC_COMPILER> <OBJECTS>")
endif()


set(CMAKE_RUC_INFORMATION_LOADED 1)
