name: testing
on: [push, pull_request]
jobs:
  test:
    runs-on: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Run test script
        run: ./scripts/test.sh
        shell: bash
